# Generated by Django 4.1.2 on 2022-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('date_posted', models.DateField(verbose_name='Date posted')),
            ],
        ),
    ]
